version: '3.3'

services:
  kafka:
    image: spotify/kafka
    container_name: kafka
    ports: 
      - "2181:2181" 
      - "9092:9092"
    environment:
      - ADVERTISED_HOST:kafka
      - ADVERTISED_PORT=9092
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
volumes:
  elastic-data:
    driver: local
  kafka-data:
    driver: local
  redis-data:
    driver: local